apiVersion: v1
kind: Pod
metadata:
  name: catapimbas
spec:
  containers:
  - name: girosflin 
    image: ubuntu
    args:
    - sleep
    - infinity
    ports:
    - containerPort: 8080
    resources:
      limits:
        memory: "128Mi"
        cpu: "0.5"
      requests:
        memory: "64Mi"
        cpu: "0.3"
  - name: busybox
    image: busybox
    args: 
     - sleep
     - "1800"
    volumeMounts:
    - name: quevolume
      mountPath: /giroflinstones
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: quevolume
    emptyDir:
      sizeLimit: 512Mi
