apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: node-exporter-daemonset-catapimbas
  name: node-exporter-daemonset-catapimbas
spec:
  selector:
    matchLabels:
      app: node-exporter-daemonset-catapimbas
  template:
    metadata:
      labels:
        app: node-exporter-daemonset-catapimbas
    spec:
      hostNetwork: true
      containers:
      - name: node-exporter-catapimbas
        image: prom/node-exporter:v1.4.1
        resources:
          limits:
            cpu: "0.5"
            memory: 256Mi
          requests:
            cpu: "0.2"
            memory: 128Mi
        ports:
        - containerPort: 9100
          hostPort: 9100
        volumeMounts:
        - name: proc
          mountPath: /host/proc
          readOnly: true
        - name: sys
          mountPath: /host/sys
          readOnly: true
      volumes:
      - name: proc
        hostPath:
          path: /proc
      - name: sys
        hostPath:
          path: /sys 
